from datetime import datetime

TICKER = "RIY INDEX"
START_DATE = datetime(2000,1,3).date()
END_DATE =  datetime(2024,3,1).date()
REBALANCING_FREQUENCY = 'monthly'
REBALANCING_MOMENT = 'end'
USE_PICKLE_UNIVERSE = True
CURRENCY ="USD"
STEP_VOL = 6
STEP_SLOPE = 1
RISK_FREE_RATE_TICKER = "US0003M Index"
SLOPE_ALPHA = 0.02

WEIGHTS_TYPE = "Equally Weighted"
